---

- name: Upgrade all packages
  yum: name=* state=latest update_cache=yes

- name: Create required groups for Oracle Database
  group: "name={{ item }} state=present"
  with_items:
    - oinstall
    - dba

- name: Create required user for Oracle Database
  user: name=oracle group=oinstall groups=dba
    password=$6$9GQdw.gCtjfFdzDP$SqT2cgEYYpj2WdejapgezYl2gOgiVKTHC/xguDqmZ71QZyS0w13dv1.ABz2VIiDLWKQ05kil5WHM1c2tJ5UTw/

- name: Copy updated sysctl.conf
  copy: src=sysctl.conf dest=/etc/ owner=root group=root

- name: Read and apply the values set in sysctl.conf
  shell: "{{ item }}"
  with_items:
    - sysctl -p
    - sysctl -a

- name: Specify limits for oracle user
  lineinfile: "dest=/etc/security/limits.conf insertbefore='# End of file'
    line={{ item }}"
  with_items:
    - "oracle soft nproc 2047"
    - "oracle hard nproc 16384"
    - "oracle soft nofile 1024"
    - "oracle hard nofile 65536"

- name: Create installation directory for Oracle Database
  file: path=/stage/ state=directory

- name: Install zip and unzip packages
  yum: "name={{ item }} state=present"
  with_items:
    - zip
    - unzip

- name: Copy and unpack Oracle Database packages
  unarchive: "src={{ item }} dest=/stage/ copy=yes
    owner=oracle group=oinstall"
  with_items:
    - linuxamd64_12102_database_1of2.zip
    - linuxamd64_12102_database_2of2.zip

- name: Create additional directories for software and database files
  file: "path={{ item }} state=directory owner=oracle group=oinstall
    mode=0775"
  with_items:
    - /u01
    - /u02

- name: Install required packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - binutils.x86_64
    - compat-libcap1.x86_64
    - gcc.x86_64
    - gcc-c++.x86_64
    - glibc.i686
    - glibc.x86_64
    - glibc-devel.i686
    - glibc-devel.x86_64
    - ksh
    - compat-libstdc++-33
    - libaio.i686
    - libaio.x86_64
    - libaio-devel.i686
    - libaio-devel.x86_64
    - libgcc.i686
    - libgcc.x86_64
    - libstdc++.i686
    - libstdc++.x86_64
    - libstdc++-devel.i686
    - libstdc++-devel.x86_64
    - libXi.i686
    - libXi.x86_64
    - libXtst.i686
    - libXtst.x86_64
    - make.x86_64
    - sysstat.x86_64

- name: Install "X Window System" package group
  yum: name="@X Window System" state=present update_cache=yes

    #- name: Copy all required files
    #copy: src=Disk1 dest=/tmp

    #- name: Install Oracle Database XE from package
    #yum: name=/tmp/Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm

    #- name: Create xe_logs directory
    #file: path=/xe_logs state=directory

    # Now we need to configure Oracle in silent mode
    #- name: Configure Oracle Database XE in silent mode
    #shell: /etc/init.d/oracle-xe configure \
    #responseFile=/tmp/Disk1/response/xe.rsp > \
    #/xe_logs/XEsilentinstall.log
