---

- name: Upgrade all packages
  yum: name=* state=latest update_cache=yes

- name: Create required groups for Oracle Database
  group: "name={{ item }} state=present"
  with_items:
    - oinstall
    - dba

# Password is 'oracle'
- name: Create required user for Oracle Database
  user: name=oracle group=oinstall groups=dba
    password=$6$9GQdw.gCtjfFdzDP$SqT2cgEYYpj2WdejapgezYl2gOgiVKTHC/xguDqmZ71QZyS0w13dv1.ABz2VIiDLWKQ05kil5WHM1c2tJ5UTw/

- name: Copy updated sysctl.conf
  copy: src=sysctl.conf dest=/etc/ owner=root group=root

- name: Read and apply the values set in sysctl.conf
  shell: "{{ item }}"
  with_items:
    - sysctl -p
    - sysctl -a

- name: Specify limits for oracle user
  lineinfile: "dest=/etc/security/limits.conf insertbefore='# End of file'
    line={{ item }}"
  with_items:
    - "oracle soft nproc 2047"
    - "oracle hard nproc 16384"
    - "oracle soft nofile 1024"
    - "oracle hard nofile 65536"

- name: Create installation directory for Oracle Database
  file: path=/stage/ state=directory

- name: Install zip and unzip packages
  yum: "name={{ item }} state=present"
  with_items:
    - zip
    - unzip

- name: Copy and unpack Oracle Database packages
  unarchive: src=oracle-xe-11.2.0-1.0.x86_64.rpm.zip dest=/stage/ copy=yes
    owner=oracle group=oinstall

- name: Install required packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - bc.x86_64
    - binutils.x86_64
    - gcc.x86_64
    - gcc-c++.x86_64
    - glibc.x86_64
    - glibc-devel.x86_64
    - libaio.x86_64
    - libaio-devel.x86_64
    - make.x86_64

- name: Copy the response file needed for silent installation of Oracle DB
  copy: src=xe.rsp dest=/stage/ owner=oracle group=oinstall

- name: Create log directory
  file: path=/xe_logs state=directory owner=oracle group=oinstall

- name: Create log file
  file: path=/xe_logs/XEsilentinstall.log state=touch owner=oracle group=oinstall

- name: Install Oracle XE 11g from package
  shell: rpm -ivh /stage/Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm > \
    /xe_logs/XEsilentinstall.log
  become_user: root

- name: Set Oracle DB XE environment variables
  shell: /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh
  become_user: oracle

- name: Set Oracle DB XE environment variables on each login and in a new shell
  lineinfile: dest=/home/oracle/{{ item }}
    line='. /u01/app/oracle/product/11.2.0/xe/bin/oracle_env.sh'
  become_user: oracle
  with_items:
    - .bashrc
    - .bash_profile

- name: Start Oracle XE database
  shell: /etc/init.d/oracle-xe start
  become_user: root
