---

- name: Copy certificates to a component's config directory
  command: cp /opt/zato/ca/* /env/{{ item }}/config/repo/

- name: Copy LB's config file
  template: src=lb-agent.conf.j2
            dest=/opt/zato/env/zato-lb/config/repo/lb-agent.conf
            owner=zato group=zato
  when: {{ hostvars[inventory_hostname]['alias'] }} == "zato_load_balancer"

- name: Copy WA's config file
  template: src=web-admin.conf.j2
            dest=/opt/zato/env/zato-wa/config/repo/web-admin.conf
            owner=zato group=zato
  when: {{ hostvars[inventory_hostname]['alias'] }} == "zato_web_admin"

- name: Copy servers' config files
  template: "src={{ item }}.conf.j2
             dest=/opt/zato/env/{{ item }}/config/repo/server.conf
             owner=zato group=zato"
  with_items: >
    - {{ hostvars[inventory_hostname]['groups']['zato-servers'] }}
  when: >
    {{ hostvars[inventory_hostname]['inventory_hostname'] }} in
    {{ hostvars[inventory_hostname]['groups']['zato-servers'] }}
