---

- name: Install BST dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
      - libjpeg-dev
      - zlib1g-dev

- name: Install virtualenv
  pip: name=virtualenv

- name: Install PyJWT using Zato's own pip
  pip: name=PyJWT executable=/opt/zato/current/bin/pip

- name: Copy zato-bst-install.sh to a remote host
  copy: src=./files/zato-bst-install.sh dest=/opt/zato/
        owner=zato
        group=zato
        mode="u+x,g+x,o+x"

- name: Install BST
  shell: ./zato-bst-install.sh /opt/zato/env/qs-1/server1 /opt/zato/env/qs-1/server2
         chdir=/opt/zato
  become_user: zato
