---
- hosts: all
  sudo: yes
  remote_user: vagrant

  tasks:

    - name: whoami
      remote_user: vagrant
      raw: whoami | tee /vagrant/whoami

    - name: install Redis
      apt: name=redis-server state=latest

    - name: install Zato helper programs
      apt: name={{ item }} state=present
      with_items:
        - apt-transport-https
        - python-software-properties
        - software-properties-common

    - name: download Zato package signing key
      get_url: url=https://zato.io/repo/zato-0CBD7F72.pgp.asc dest=/home/vagrant/

    - name: add Zato package signing key
      apt_key: file=/home/vagrant/zato-0CBD7F72.pgp.asc

    - name: add Zato repository
      apt_repository: repo='deb https://zato.io/repo/stable/2.0/ubuntu trusty main' state=present

    - name: update the system and install Zato
      apt: name=zato update_cache=yes

    - name: create quickstart directory
      file: path=/opt/zato/env/qs-1/ owner=zato group=zato state=directory
      register: qsdir

    - name: create quickstart
      raw: rm -rf /opt/zato/env/qs-1 && mkdir -p /opt/zato/env/qs-1 && /opt/zato/2.0.2/bin/zato quickstart create /opt/zato/env/qs-1 sqlite localhost 6379 --kvdb_password '' --verbose

    - name: create a directory to store test results
      file: path=/vagrant/tests owner=vagrant group=vagrant state=directory

    - name: start Zato load balancer
      remote_user: vagrant
      raw: /opt/zato/2.0.2/bin/zato start /opt/zato/env/qs-1/load-balancer &&
           /opt/zato/2.0.2/bin/zato info /opt/zato/env/qs-1/load-balancer | tee /vagrant/tests/lb-info
