---

- name: download Zato package signing key
  get_url: url=https://zato.io/repo/zato-0CBD7F72.pgp.asc dest=/home/vagrant/
  remote_user: vagrant

- name: add Zato package signing key
  apt_key: file=/home/vagrant/zato-0CBD7F72.pgp.asc

- name: add Zato repository
  apt_repository: repo='deb https://zato.io/repo/stable/2.0/ubuntu trusty main' state=present
