---

- name: create quickstart directory
  file: path=/opt/zato/env/qs-1/ owner=zato group=zato state=directory
  sudo_user: zato

- name: create quickstart
  shell: rm -rf /opt/zato/env/qs-1 && mkdir -p /opt/zato/env/qs-1 && /opt/zato/2.0.2/bin/zato quickstart create /opt/zato/env/qs-1 sqlite localhost 6379 --kvdb_password '' --verbose
  sudo_user: zato

- name: create a directory to store test results
  file: path=/opt/zato/tests owner=zato group=zato state=directory
  sudo_user: zato

- name: create symlinks to Zato startup scripts
  file: src=/opt/zato/env/qs-1/{{ item }} dest=/etc/zato/components-enabled/{{ item }} state=link
  with_items:
    - load-balancer
    - server1
    - server2
    - web-admin
