---

- name: Get repo list
  shell: aptly publish list -raw
  register: published_list

- name: Get snapshot list
  shell: aptly snapshot list -raw -sort='time'
  register: snap_list

- name: Get package list
  shell: aptly repo search {{ repository }} {{ zato_package }}
  register: pack_list
  ignore_errors: true

- name: Add the package to aptly repository
  shell: aptly repo add {{ repository }} {{ incoming }}/{{ zato_package }}
  when:
    "'{{ zato_package }}' not in pack_list.stdout"
  register: add_pkg

- name: Create a snapshot of a repo
  shell: aptly snapshot create {{ snapshot }} from repo {{ repository }}
  when: add_pkg.changed
  register: create_snap

- name: Publish the snapshot
  shell: aptly publish snapshot {{ snapshot }} {{ prefix }}
  when:
    "'{{ prefix }} {{ package['codename'] }}' not in published_list.stdout"
  register: publish_starter

- name: Switch to the snapshot
  shell: aptly publish switch {{ package['codename'] }} {{ prefix }} {{ snapshot }}
  register: switch_repo
  when: >
    create_snap.changed and
    not publish_starter.changed
    and "'{{ prefix }}' in published_list.stdout"

- name: Copy published repo to /var/www/repo directory
  shell: cp -r {{ source_dir }} /var/www/repo/{{ package['release'] }}/2.0/
  become_user: root
