---

# Let's check first if the deb package isn't already in the local repo,
# and only then add it.
- name: Get list of packages in the local repository
  shell: aptly repo search \
         zato-{{ package['release'] }}-{{ package['codename'] }} zato
  register: package_list
  ignore_errors: True

- name: Add the package to aptly repository
  shell: aptly repo add zato-{{ package['release'] }}-{{ package['codename'] }} \
    /opt/aptly/incoming/{{ package['distro'] }}/{{ package['codename'] }}/zato-{{ package['version'] }}-{{ package['release'] }}_{{ package['arch'] }}-{{ package['codename'] }}.{{ package['format'] }}
  when:
      "'zato_{{ package['version'] }}-{{ package['release'] }}-{{ package['codename'] }}_{{ package['arch'] }}' not in package_list.stdout"
  register: package_added

- name: Create a snapshot of the repository
  shell: aptly snapshot create \
    snap-zato-{{ package['release'] }}-{{ package['codename'] }}-{{ repo_datetime }} \
    from repo zato-{{ package['release'] }}-{{ package['codename'] }}
  when: package_added.changed == True
  register: snapshot_created

# Check if there is any previous repo
# on this host; this is in case this
# playbook is being run for the first time
# on a host
- name: Get a list of published repos
  shell: aptly publish list
  register: repo_list

- name: Drop the previous published repo (if it exists)
  shell: aptly publish drop {{ package['codename'] }} \
         repo/{{ package['release'] }}/2.0/{{ package['distro'] }}
  when:
    "'repo/{{ package['release'] }}/2.0/{{ package['distro'] }}/{{ package['codename'] }}' in repo_list.stdout"

- name: Publish the snapshot
  shell: aptly publish snapshot \
    snap-zato-{{ package['release'] }}-{{ package['codename'] }}-{{ repo_datetime }} \
    repo/{{ package['release'] }}/2.0/{{ package['distro'] }}
  register: snapshot_published
  when: snapshot_created.changed == True

- name: Copy published repo to /var/www/repo directory
  shell: cp -r /opt/aptly/.aptly/public/repo/{{ package['release'] }}/2.0/{{ package['distro'] }}/ \
        /var/www/repo/{{ package['release'] }}/2.0/
  become_user: root
  when: snapshot_published.changed == True
