---

- name: Configure Oracle 11g
  shell: /etc/init.d/oracle-xe configure responseFile=/stage/xe.rsp
  become_user: root

- name: Copy sql scripts
  copy: src={{ item }} dest=/u01/app/oracle owner=oracle group=oinstall
  with_items:
    - set_access.sql
    - create_zato_user.sql
    - create_zato_db.sql
    - startup.sql

- name: Create zato user
  script: create_zato_user.sh

- name: Create zato database
  script: create_zato_db.sh

- name: Set access to Oracle DB for remote clients
  script: set_access.sh
