---

- name: create quickstart directory
  file: path=/opt/zato/env/qs-1/
        owner=zato
        group=zato
        state=directory

- name: create quickstart on Debian-based systems
  shell: /opt/zato/current/bin/zato quickstart create \
         --odb_host 10.2.4.11 \
         --odb_port 1521 \
         --odb_user zato1 \
         --odb_db_name zato1 \
         --odb_password 'zato1' \
         --kvdb_password '' \
         /opt/zato/env/qs-1 oracle localhost 6379
         --verbose
  become_user: zato
  when: ansible_os_family == "Debian"

- name: create quickstart on CentOS-based systems
  shell: /opt/zato/current/code/bin/zato quickstart create \
         --odb_host "{{ oracle_box }}" \
         --odb_port 1521 \
         --odb_user zato
         --odb_db_name ZATO \
         --odb_password 'zato1AsW2' \
         --kvdb_password '' \
         /opt/zato/env/qs-1 oracle localhost 6379 \
         --verbose
  become_user: zato
  when: ansible_distribution == "CentOS"

- name: create symlinks to Zato startup scripts
  file: src=/opt/zato/env/qs-1/{{ item }}
        dest=/etc/zato/components-enabled/{{ item }} 
        state=link
  with_items:
    - load-balancer
    - server1
    - server2
    - web-admin

- name: start Zato components as services
  service: name=zato state=restarted enabled=yes
