---

- name: Install alien package to convert rpm into deb
  apt: name=alien state=present
  when: ansible_os_family == "Debian"

- name: Install libaio1 package
  apt: name=libaio1 state=present
  when: ansible_os_family == "Debian"

- name: Copy Oracle Instant Client packages to x86_64 systems
  copy: "src={{ item }}
    dest=/home/{{ user }} owner={{ user }} group={{ user }}"
  when: ansible_architecture == "x86_64"
  with_items:
    - "{{ db_client['pkg'] }}"
    - "{{ db_client['devel'] }}"
    - "{{ db_client['sqlplus'] }}"

- name: Copy Oracle Instant Client packages to i386 systems
  copy: "src={{ item }}
    dest=/home/{{ user }} owner={{ user }} group={{ user }}"
  when: ansible_architecture == "i386"
  with_items:
    - "{{ db_client['pkg32'] }}"
    - "{{ db_client['devel32'] }}"
    - "{{ db_client['sqlplus32'] }}"

- name: Convert OIC rpm packages to debs
  shell: alien -i "{{ item }}"
  when: ansible_os_family == "Debian"
  with_items:
    - "{{ db_client['pkg'] }}"
    - "{{ db_client['devel'] }}"
    - "{{ db_client['sqlplus'] }}"
  become_user: root

- name: Install cx_Oracle pip package
  shell: /opt/zato/current/bin/pip install cx_Oracle
  become_user: zato
