---

ip: 
servers:
  server1:
    port: 17010
    workers: 1
    component_path: /opt/zato/env/server1
  server2:
    port: 17011
    workers: 1
    component_path: /opt/zato/env/server2
  server3:
    port: 17012
    workers: 1
    component_path: /opt/zato/env/server3
  server4:
    port: 17013
    workers: 1
    component_path: /opt/zato/env/server4
