---

- name: Create a directory to store a component's certificate and keys
  file: path=/opt/zato/ca state=directory owner=zato group=zato

- name: Distribute certificates among Zato components
  copy: "src={{ item }} dest=/opt/zato/ca owner=zato group=zato"
  with_items:
    - "{{ hostvars[inventory_hostname]['cert'] }}"
    - "{{ hostvars[inventory_hostname]['private_key'] }}"
    - "{{ hostvars[inventory_hostname]['public_key'] }}"
