---

- name: Create a directory for Zato web admin
  file: path={{ path }}
    owner=zato group=zato
    state=directory

- name: Generate zato_web_admin.config file
  template: src=zato_web_admin.j2 dest=/opt/zato/zato_web_admin.config
    owner=zato group=zato

- name: Create Zato web admin
  command: ./current/bin/zato from-config zato_web_admin.config
    chdir=/opt/zato
  become_user: zato

- name: Create a symlink to Zato startup script
  file: src={{ path }}
    dest=/etc/zato/components-enabled/web-admin
    state=link

- name: Start Zato web admin as a service
  service: name=zato state=started enabled=yes

- pause: seconds=15

- name: Generate uuid to be used as a password
  shell: uuidgen > web_admin_password.txt chdir=/opt/zato
  become_user: zato

- name: Generate a config file to update web-admin password from
  template: src=update_password.config dest=/opt/zato/update_password.config
    owner=zato group=zato

- name: Append a new password to update_password.config
  shell: echo 'password'=$(cat /opt/zato/web_admin_password.txt) \
    >> /opt/zato/update_password.config
    chdir=/opt/zato
  become_user: zato

- name: Update web-admin password
  shell: /opt/zato/current/bin/zato from-config /opt/zato/update_password.config
    chdir={{ env_path }}
  become_user: zato
