---

- name: Create a directory for Zato web admin
  file: path={{ path }}
    owner=zato group=zato
    state=directory
  become_user: zato

- name: Generate zato_web_admin.config file
  template: src=zato_web_admin.j2 dest=/opt/zato/zato_web_admin.config
    owner=zato group=zato

- name: Create Zato web admin
  command: ./current/bin/zato from-config zato_web_admin.config
    chdir=/opt/zato
  become_user: zato

- name: Create a symlink to Zato startup script
  file: src={{ path }}
    dest=/etc/zato/components-enabled/web-admin
    state=link

- name: Start Zato web admin as a service
  service: name=zato state=started enabled=yes

- pause: seconds=15
