---

- name: Create a directory for Zato load balancer
  file: path={{ path }}
    owner=zato group=zato
    state=directory

- name: Generate zato_load_balancer.config file
  template: src=zato_load_balancer.j2 dest=/opt/zato/zato_load_balancer.config
    owner=zato group=zato

- name: Create Zato load balancer
  command: ./current/bin/zato from-config zato_load_balancer.config
    chdir=/opt/zato
  become_user: zato

- name: Create a symlink to Zato startup script
  file: src={{ path }}
    dest=/etc/zato/components-enabled/load-balancer
    state=link

- name: Start Zato load balancer as a service
  service: name=zato state=started enabled=yes

- pause: seconds=15
