---

  - name: Install required packages
    apt: name={{ item }} state=present
    with_items:
      - build-essential
      - tcl8.5

  - name: Download Redis
    get_url: url=http://download.redis.io/releases/redis-stable.tar.gz dest=./

  - name: Unpack Redis
    unarchive: src=./redis-stable.tar.gz dest=./ copy=no

  - name: Compile Redis
    shell: make chdir=./redis-stable

  - name: Install Redis
    shell: make install chdir=./redis-stable

  - name: Configure Redis to run in the background
    shell: echo -n | ./install_server.sh chdir=./redis-stable/utils

  - name: Run Redis
    service: name=redis_6379 state=started
