---

  - include: install.yml
    when: >
      ansible_distribution_version == "14.04" or
      ansible_distribution_version == "16.04" or
      ansible_distribution_version == "8.1"

  - include: install_from_source.yml
    when: ansible_distribution == "Debian" or ansible_distribution_version == "12.04"

  - include: install_on_redhat.yml
    when: ansible_distribution == "CentOS"
