---

- hosts: localhost
  vars_files:
    - vars/main.yml

  tasks:

    - name: Make sure a repo box is running
      shell: vagrant up chdir=./vm/{{ repo['host'] }}

    - name: Copy vagrant user's private key
      shell: cp  ./.vagrant/machines/default/virtualbox/private_key \
             ../../files/vagrant_key/
             chdir=./vm/{{ repo['host'] }}

- hosts: "{{ repo['host'] }}"
  become: True
  vars_files:
    - vars/main.yml

  tasks:

    - name: Fetch deb repo box's certificate
      fetch: dest=./roles/prepare_install_zato/files/ \
             src=/etc/apache2/ssl/{{ repo['host'] }}.crt
             flat=yes
             fail_on_missing=yes
      when: ansible_os_family == "Debian"

    - name: Fetch rpm repo box's certificate
      fetch: dest=./roles/prepare_install_zato/files/ \
             src=/etc/httpd/ssl/{{ repo['host'] }}.crt
             flat=yes
             fail_on_missing=yes
      when: ansible_distribution == "CentOS"

- hosts: "{{ repo['host'] }}"
  become: True
  vars:
    repo_datetime: "{{ ansible_date_time.iso8601 }}"
  vars_files:
    - vars/main.yml

  roles:

    - add_package_to_repo
