---

# This playbook is only to be used with Vagrant boxes. It simply creates
# a new user and enables SSH connection with a box by adding user's SSH keys
# to authorized_keys file in the box.

- hosts: postgresql, redis-ha, zato-components
  become: True
  remote_user: vagrant
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    ansible_ssh_private_key_file:
      ./files/vagrant_key/distributed/{{ hostvars[inventory_hostname]['inventory_hostname'] }}_private_key

  tasks:

    - name: Install whois package
      apt: name=whois state=present

    - name: Generate a password for a user
      shell: mkpasswd --method=SHA-512 {{ user }}
      register: password

    - name: Create a custom group
      group: name={{ user }} state=present

    - name: Create a custom user
      user: name={{ user }} comment="Builds and tests Zato packages"
        state=present
        group={{ user }}
        groups="{{ user }},adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare"
        password={{ password.stderr }}
        shell=/bin/bash

    - name: Add the user's SSH pub key to authorized keys
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}"
