---

# This playbook distributes keys and certificates for Zato components,
# creates those components and starts them, and then reconfigures them
# and finally restarts them.
- hosts: zato-components
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    servers: "{{ hostvars[inventory_hostname]['groups']['zato-servers'] }}"
    first_server: "{{ hostvars[inventory_hostname]['groups']['zato-servers'][0] }}"

  roles:

    - distribute_zato_certs
    - create_zato_components
    - configure_zato_distributed
