---

# This playbook is meant to be used in a distributed Zato environment
# to create and distribute self-signed CA and keys and certificates.

- hosts: localhost

  roles:

    - create_zato_certs

- hosts: zato-components:!zato-odb
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    servers: "{{ hostvars[inventory_hostname]['groups']['zato-servers'] }}"
    first_server: "{{ hostvars[inventory_hostname]['groups']['zato-servers'][0] }}"

  roles:

    - distribute_zato_certs
