---

- hosts: load-balancer, web-admin, zato-servers
  become: True

  roles:

    - install_zato_dependencies
    - prepare_install_zatoio
    - install_zato

  tasks:

    - name: Install acl package
      apt: name=acl state=present update_cache=yes

- hosts: load-balancer
  become: True

  roles:

    - create_zato_odb
    - create_zato_cluster

- hosts: localhost

  roles:

    - generate_ca

- hosts: load-balancer
  become: True

  roles:

    - create_zato_lb

- hosts: web-admin
  become: True

  roles:

    - create_zato_wa

- hosts: zato-servers
  become: True

  roles:

    - create_zato_server
    - configure_zato_server

- hosts: load-balancer
  become: True

  roles:

    - configure_zato_lb
