---

- hosts: localhost

  tasks:

    - name: Copy CA so that it is available for add_zato_servers role
      shell: cp ./roles/create_zato_server/files/{{ item }} \
        ./roles/add_zato_servers/files
      with_items:
        - ca_cert.pem
        - zato_ca.key.pem

- hosts: zato-servers
  become: True

  tasks:

    - name: Install acl package
      apt: name=acl state=present update_cache=yes

- hosts: zato-servers
  become: True

  roles:

    - install_zato_dependencies
    - prepare_install_zatoio
    - install_zato
    - add_zato_servers

- hosts: load-balancer
  become: True

  roles:

    - configure_zato_lb
