---

# The purpose of this playbook is to install Zato in a larger group of boxes
# specified under 'hosts' variable. For example, it is possible to pass
# 'zato-components' as the hosts pattern, but it has to be defined first
# in the inventory file.

- hosts: zato-components, zato-odb
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"

  roles:

    - install_zato_dependencies
    - { role: prepare_install_zato, when: repo.host == "repo-box-ubuntu" or
        repo.host == "repo-box-centos" }
    - { role: prepare_install_zatoio, when: repo.host == "zato.io" }
    - install_zato
