---

# This playbook creates Vagrant boxes for Zato distributed environment
# consisting of Zato ODB server, Redis HA (3 servers), and Zato components:
# load balancer, web admin and two servers.

- hosts: localhost
  vars_files:
    - group_vars/zato-components/all.yml
    - host_vars/zato-odb.yml
    - host_vars/redis1.yml
    - host_vars/redis2.yml
    - host_vars/redis3.yml
    - host_vars/zato-server1.yml
    - host_vars/zato-server2.yml
    - host_vars/zato-lb.yml
    - host_vars/zato-wa.yml

  tasks:

    - name: Create box root directory
      file:
        name=./vm/distributed/{{ item }}/
        state=directory
      with_items:
        - "{{ groups['redis-ha'] }}"
        - "{{ groups['zato-components'] }}"

    - name: Prepare Vagrantfile
      template: src=./templates/box_distributed.j2
                dest=vm/distributed/{{ item }}/Vagrantfile
      with_items:
        - "{{ groups['redis-ha'] }}"
        - "{{ groups['zato-components'] }}"

    - name: Create a vagrant box
      shell: vagrant up chdir=./vm/distributed/{{ item }}
      with_items:
        - "{{ groups['redis-ha'] }}"
        - "{{ groups['zato-components'] }}"

    - name: Copy vagrant user's private keys
      shell: cp  ./.vagrant/machines/default/virtualbox/private_key \
             ../../../files/vagrant_key/distributed/{{ item }}_private_key
             chdir=./vm/distributed/{{ item }}/
             creates=yes
      with_items:
        - zato-odb
        - "{{ groups['redis-ha'] }}"
        - "{{ groups['zato-components'] }}"

    - name: Set the private_keys mode to 0600
      file: path=./files/vagrant_key/distributed/{{ item }}_private_key
            mode=0600
      with_items:
        - "{{ groups['redis-ha'] }}"
        - "{{ groups['zato-components'] }}"

- hosts: redis-ha, zato-components
  become: True
  remote_user: vagrant
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    ansible_ssh_private_key_file:
      ./files/vagrant_key/distributed/{{ hostvars[inventory_hostname]['inventory_hostname'] }}_private_key

  roles:

    - box_setup
