---

- hosts: postgresql
  become: True
  vars:
    ansible_host: "{{ hostvars['postgresql']['ip'] }}"
    ansible_ssh_private_key_file: ./files/vagrant_key/distributed/postgresql_private_key

  roles:

    - install_postgresql

- hosts: redis
  become: True
  vars:
    ansible_host: "{{ hostvars['redis']['ip'] }}"
    ansible_ssh_private_key_file: ./files/vagrant_key/distributed/redis_private_key

  roles:

    - install_redis

- hosts: zato-components
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    ansible_ssh_private_key_file:
      ./files/vagrant_key/distributed/{{ hostvars[inventory_hostname]['inventory_hostname'] }}_private_key
  vars_files:
    - vars/main.yml

  roles:

    - install_additional_soft
    - prepare_install_zato
    - install_zato
