---

- hosts: zato-distributed:!redis
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    ansible_ssh_private_key_file:
      ./files/vagrant_key/distributed/{{ hostvars[inventory_hostname]['inventory_hostname'] }}_private_key

  roles:

    - install_additional_soft
    - prepare_install_zato
    - install_zato

- hosts: postgresql
  become: True
  vars:
    ansible_host: "{{ hostvars['postgresql']['ip'] }}"
    ansible_ssh_private_key_file: ./files/vagrant_key/distributed/postgresql_private_key

  roles:

    - install_postgresql
    - configure_postgresql
    - create_zato_odb
    - create_zato_cluster

- hosts: redis
  become: True
  vars:
    ansible_host: "{{ hostvars['redis']['ip'] }}"
    ansible_ssh_private_key_file: ./files/vagrant_key/distributed/redis_private_key

  roles:

    - install_redis

- hosts: localhost

  roles:

    - create_zato_certs

- hosts: zato-components
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    ansible_ssh_private_key_file:
      ./files/vagrant_key/distributed/{{ hostvars[inventory_hostname]['inventory_hostname'] }}_private_key

  roles:

    - distribute_zato_certs
    - create_zato_components
