---

# This playbook installs Redis and configures HA with Redis sentinels.

- hosts: redis-ha
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"

  roles:

    - install_redis
    - configure_redis_ha
