---

- hosts: aws-zato-lb, aws-zato-wa, aws-zato-server
  become: True

  tasks:

    - name: Install acl package
      apt: name=acl state=present update_cache=yes

  roles:

    - install_zato_dependencies
    - { role: prepare_install_zato, when: repo.host == "repo-box-ubuntu" or
        repo.host == "repo-box-centos" }
    - { role: prepare_install_zatoio, when: repo.host == "zato.io"  }
    - install_zato

- hosts: aws-zato-lb
  become: True

  roles:

    - install_redis
    - create_zato_odb
    - create_zato_cluster

- hosts: localhost

  roles:

    - generate_ca

- hosts: aws-zato-lb
  become: True

  roles:

    - create_zato_lb

- hosts: aws-zato-wa
  become: True

  roles:

    - create_zato_wa
    - create_zato_server

- hosts: aws-zato-server
  become: True

  roles:

    - create_zato_server

- hosts: aws-zato-lb
  become: True

  roles:

    - configure_zato_lb

- hosts: aws-zato-wa, aws-zato-server
  become: True

  roles:

    - configure_zato_server
