---

- hosts: zato-odb
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    odb_type: "{{ odb_type }}"

  roles:

    - install_{{ odb_type }}
    - configure_{{ odb_type }}
    - create_zato_odb
    - create_zato_cluster

          #    - install_oracle
          #when: "{{ odb_type }}" == "oracle"
          #
          #- install_postgresql
          #when: "{{ odb_type }}" == "postgresql"
