---

- hosts: zato-odb
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"
    odb_type: "{{ odb_type }}"

  roles:

    - install_{{ odb_type }}
    - configure_{{ odb_type }}
