---

# This playbook is meant to be used in a distributed Zato environment
# to install and configure MySQL, and then create Zato ODB and a cluster
# on an independent box.

- hosts: zato-odb
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"

  roles:

    - install_mysql
    - configure_mysql
    - create_zato_odb_mysql
    - create_zato_cluster_mysql
