---

# This playbook is meant to be used in a distributed Zato environment
# to install and configure PostgreSQL, and then create Zato ODB and a cluster
# on an independent box.

- hosts: zato-odb
  become: True
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['ip'] }}"

  roles:

    - install_postgresql
    - configure_postgresql
    - create_zato_odb
    - create_zato_cluster
