---

- hosts: localhost
  vars_files:
      - vars/main.yml

  tasks:

    - name: Create box root directory
      file: name=./vm/{{ package['system'] }} state=directory

    - name: Prepare Vagrantfile
      template: src=./templates/box.j2
                dest=vm/{{ package['system'] }}/Vagrantfile

    - name: Create a vagrant box
      shell: vagrant up chdir=./vm/{{ package['system'] }}

    - name: Copy vagrant user's private key
      shell: cp  ./.vagrant/machines/default/virtualbox/private_key \
             ../../files/vagrant_key/
             chdir=./vm/{{ package['system'] }}/

    - name: Set the private_key mode to 0600
      file: path=./files/vagrant_key/private_key mode=0600

- hosts: "{{ box['hostname'] }}"
  become: True
  remote_user: vagrant
  vars:
    ansible_host: "{{ box['ip'] }}"
    ansible_ssh_private_key_file:
      ./files/vagrant_key/private_key
  vars_files:
    - vars/main.yml

  roles:

    - box_setup
