---

- hosts: localhost
  vars_files:
      - vars/main.yml

  tasks:

    - name: Create box root directory
      file: name=./vm/{{ package['system'] }} state=directory

    - name: Prepare Vagrantfile
      template: src=./templates/box.j2
                dest=vm/{{ package['system'] }}/Vagrantfile

    - name: Create a vagrant box
      shell: vagrant up chdir=./vm/{{ package['system'] }}

    - name: Copy vagrant user's private key
      shell: cp  ./.vagrant/machines/default/virtualbox/private_key \
             ../../files/vagrant_key/
             chdir=./vm/{{ package['system'] }}/

    - name: Set the private_key mode to 0600
      file: path=./files/vagrant_key/private_key mode=0600

- hosts: "{{ host }}"
  become: True
  remote_user: vagrant
  vars:
    ansible_ssh_private_key_file:
      ./files/vagrant_key/private_key

  tasks:

    - name: Install whois package
      apt: name=whois state=present

    - name: Generate a password for a user
      shell: mkpasswd --method=SHA-512 {{ user }}
      register: password

    - name: Create a custom group
      group: name={{ user }} state=present

    - name: Create a custom user
      user: name={{ user }} comment="Builds and tests Zato packages"
        state=present
        group={{ user }}
        groups="{{ user }},adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare"
        password={{ password.stderr }}
        shell=/bin/bash

    - name: Add the user's SSH pub key to authorized keys
      authorized_key:
        user: "{{ user }}"
        key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}"
