---

- hosts: localhost
  vars_files:
    - host_vars/oracle-box.yml

  tasks:

    - name: Create a vagrant box
      shell: vagrant up chdir=./vm/oracle_box

    - name: Copy vagrant user's private key
      shell: cp  ./.vagrant/machines/default/virtualbox/private_key \
             ../../files/vagrant_key/oracle_private_key
             chdir=./vm/oracle_box/

    - name: Set the private_key mode to 0600
      file: path=./files/vagrant_key/oracle_private_key mode=0600

- hosts: oracle-box
  become: True
  remote_user: vagrant
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['box']['ip'] }}"
    ansible_ssh_private_key_file:
      ./files/vagrant_key/oracle_private_key

  roles:

    - add_swap
    - install_oracle
    - configure_oracle

- hosts: "{{ box['hostname'] }}"
  become: True
  vars_files:
    - vars/main.yml
  vars:
    - db_client:
        pkg: oracle-instantclient12.1-basiclite-12.1.0.2.0-1.x86_64.rpm
        devel: oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm
        sqlplus: oracle-instantclient12.1-sqlplus-12.1.0.2.0-1.x86_64.rpm

  roles:

    - install_zato_dependencies
    - install_redis
    - prepare_install_zato
    - install_zato
    - create_quickstart_oracle
    - test_quickstart
