---

- hosts: "{{ box['hostname'] }}"
  become: True
  vars_files:
    - vars/main.yml

  roles:

    - install_additional_soft
    - install_redis
    - install_mysql
    - configure_mysql
    - prepare_install_zato
    - install_zato
    - create_quickstart_mysql
    - test_quickstart
