---

- hosts: aptly-test-box
  vars_files:
      - vars/vars.yml
      - vars/parameters.yml
  become: True
  become_user: aptly

  roles:

      - add_package_to_repo

- include:  prepare_test_box.yml
  vars_files:
      - vars/parameters.yml
      - vars/vars.yml

- hosts: "{{ host }}"
  become: True
  vars_files:
      - vars/vars.yml
      - vars/parameters.yml

  roles:

      - prepare_install_zato

- hosts: "{{ host }}"
  become: True
  vars_files:
      - vars/vars.yml
      - roles/test_aptly/vars/latest.yml

  roles:

      - { role: test_aptly, version: "" }

- include: clean.yml
  vars_files:
      - vars/parameters.yml
      - vars/vars.yml

- include:  prepare_test_box.yml
  vars_files:
      - vars/parameters.yml
      - vars/vars.yml

- hosts: "{{ host }}"
  become: True
  vars_files:
      - vars/vars.yml
      - roles/test_aptly/vars/previous.yml

  roles:

      - prepare_install_zato
      - { role: test_aptly,
          version: "={{ release_version }}-{{ package_version }}-{{ codename }}" }

- include: clean.yml
  vars_files:
      - vars/parameters.yml
      - vars/vars.yml

- include:  prepare_test_box.yml
  vars_files:
      - vars/parameters.yml
      - vars/vars.yml

- hosts: "{{ host }}"
  become: True
  vars_files:
      - vars/vars.yml
      - roles/test_aptly/vars/latest.yml

  roles:

      - prepare_install_zato
      - { role: test_aptly,
          version: "={{ release_version }}-{{ package_version }}-{{ codename }}" }

- include: clean.yml
  vars_files:
      - vars/parameters.yml
      - vars/vars.yml
