---

- name: Install postgresql-client
  apt: name=postgresql-client state=present
  become_user: root

- name: Generate pgpass file to connect with an ODB non-interactively
  template: "src={{ role_path }}/templates/.pgpass.j2 
    dest=/opt/zato/.pgpass
    owner=zato group=zato mode=0600"

- name: Check if a server exists
  shell: psql -h {{ odb['host'] }} -p {{ odb[odb_type]['port'] }} \
    -U {{ odb['user'] }} -d {{ odb['name'] }} \
    -c 'SELECT EXISTS(SELECT 1 FROM server WHERE server.name = {{ server.key }} LIMIT 1)'
  with_dict: '{{ servers }}'
  loop_control:
    loop_var: server
  become_user: zato
