---

- name: Create a directory for Zato server
  file: path={{ path }}
    owner=zato group=zato
    state=directory

- name: Generate zato_server.config file
  template: src={{ role_path }}/templates/zato_server.j2 \
    dest=/opt/zato/zato_server.config
    owner=zato group=zato

- name: Create Zato server
  command: ./current/bin/zato from-config zato_server.config
    chdir=/opt/zato
  become_user: zato

- name: Create a symlink to Zato startup script
  file: src={{ path }}
    dest=/etc/zato/components-enabled/server
    state=link

- name: Start a Zato server as a service
  service: name=zato state=started enabled=yes

- pause: seconds=30
