---

- name: Create database 'zato' user
  mysql_user: name=zato
              password=zato
              priv=zato.*:ALL,GRANT
              state=present

- name: Create 'zato' database
  mysql_db: name=zato
            state=present
            login_user=zato
            login_password=zato

- name: Set bind-address in MySQL config file
  lineinfile: "dest=/etc/mysql/my.cnf line='bind-address = 10.5.5.71'
    regexp='bind-address'
    state=present"

- name: Restart mysql service
  service: name=mysql state=restarted

- name: Allow access to 'zato' DB from remote hosts
  shell: mysql -u root -e "GRANT ALL ON zato.* TO 'zato'@'10.5.5.%'
    IDENTIFIED BY 'zato';"
